# --- Navigation and Mouse Controls ---
MBTN_LEFT cycle pause;script-message-to uosc flash-pause-indicator #@click
TAB script-message-to uosc toggle-ui #@press
TAB script-message-ui #@release-to uosc toggle

; playlist-prev
' playlist-next
ALT+d cycle deband  
MOUSE_BTN2 script-binding uosc/menu-blurred 
ALT+a script-message-to uosc show-submenu-blurred "Open"
ALT+z script-message-to uosc show-submenu-blurred "Audio"
ALT+x script-message-to uosc show-submenu-blurred "Subtitles"
ALT+s script-message-to uosc show-submenu-blurred "Video > Shaders"

### UOSC Menu Config ###

# Open Menu
b script-binding uosc/open-file                                 #! Open > Open File

# Video Menu
g cycle interpolation                                           #! Video > Toggle Interpolation
ALT+v vf toggle deblock=filter=weak:block=4                     #! Video > Filters > Toggle Deblocking

# Shaders Sub-Menu
n change-list glsl-shaders toggle ~~/shaders/nlmeans_luma.glsl  #! Video > Shaders > Denoise
; change-list glsl-shaders toggle ~~/shaders/adasharp_luma.glsl  #! Video > Shaders > Sharpen 
; apply-profile Anime-1080p-1440p                               #! Video > Shaders > Anime > Modern Anime (1080p)
; apply-profile Nuvex-480p-1440p-Cel                            #! Video > Shaders > Anime > Cel Remaster (480p)

# IGV Shaders
; change-list glsl-shaders toggle ~~/shaders/krigbl.glsl        #! Video > Shaders > igv > krigbl
; change-list glsl-shaders toggle ~~/shaders/F8.glsl            #! Video > Shaders > igv > FSRCNNX 8
; change-list glsl-shaders toggle ~~/shaders/ssimsr.glsl        #! Video > Shaders > igv > SSimSuperRes

# Profiles Menu
CTRL+1 apply-profile FSRCNNX;show-text "Profile: FSRCNNX"       #! Video > Profiles > FSRCNNX
CTRL+2 apply-profile FSRCNNX+;show-text "Profile: FSRCNNX+"     #! Video > Profiles > FSRCNNX+
CTRL+3 apply-profile Ravu-Zoom;show-text "Profile: Ravu-Zoom"   #! Video > Profiles > Ravu-Zoom
CTRL+4 apply-profile Ani4k;show-text "Profile: Ani4k"           #! Video > Profiles > Ani4k
CTRL+5 apply-profile AniSD;show-text "Profile: AniSD"           #! Video > Profiles > AniSD
CTRL+6 apply-profile Anime4K;show-text "Profile: Anime4K"       #! Video > Profiles > Anime4k
CTRL+7 apply-profile NNEDI3;show-text "Profile: NNEDI3"         #! Video > Profiles > NNEDI3
CTRL+8 apply-profile NNEDI3+;show-text "Profile: NNEDI3+"       #! Video > Profiles > NNEDI3+
c change-list glsl-shaders clr all                              #! Video > Shaders > Clear All

# Audio Menu
F1 af toggle "lavfi=[loudnorm=I=-14:TP=-3:LRA=4]"               #! Audio > Dialogue

# Subtitles Menu
y script-binding uosc/load-subtitles                            #! Subtitles > Load
Y script-binding uosc/subtitles                                 #! Subtitles > Select
ALT+j add sub-scale +0.05                                       #! Subtitles > Bigger
ALT+k add sub-scale -0.05                                       #! Subtitles > Smaller
z add sub-delay -0.1                                            #! Subtitles > Decrease Delay
x add sub-delay  0.1                                            #! Subtitles > Increase Delay

# Tools & Exit
/ script-binding console/enable                                 #! Tools > Console
a cycle window-minimized                                        #! Minimise
q quit-watch-later                                              #! Exit
Q quit                                                          #! Force Quit
