[Deband-Medium]
deband-iterations=2
deband-threshold=64
deband-range=16
deband-grain=24

[Deband-Strong]
deband-iterations=3
deband-threshold=64
deband-range=16
deband-grain=24

[NNEDI3]
profile-desc=Suitable for most scenarios
glsl-shaders="~~/shaders/nnedi3_nns32_win8x4.glsl;~~/shaders/adasharp_luma.glsl"

[NNEDI3+]
profile-desc=Suitable for most scenarios
glsl-shaders="~~/shaders/nnedi3_nns64_win8x4.glsl;~~/shaders/adasharp_luma.glsl"

[Ravu-Zoom]
profile-desc=Suitable for most scenarios 
glsl-shaders="~~/shaders/ravu_z_ar_r3.glsl;~~/shaders/adasharp_luma.glsl"

[FSRCNNX]
profile-desc=Suitable for HD live action
glsl-shaders="~~/shaders/F8.glsl;~~/shaders/adasharp_luma.glsl"

[FSRCNNX+]
profile-desc=Suitable for SD live action
glsl-shaders="~~/shaders/nnedi3_nns32_win8x4.glsl;~~/shaders/F16.glsl"
    
[Ani4k]
profile-desc=Suitable for most anime
glsl-shaders="~~/shaders/Ani4Kv2_ArtCNN_C4F32_i2.glsl"

[AniSD]
profile-desc=Suitable for SD anime
glsl-shaders="~~/shaders/AniSD_ArtCNN_C4F32_i4.glsl"

[Anime4K]
profile-desc=Suitable for most anime
glsl-shaders="~~/shaders/krigbl.glsl;~~/shaders/A4K_Restore_CNN_Soft_M.glsl;~~/shaders/A4K_Clamp_Highlights.glsl"

[Anime-1080p-1440p]
profile-desc=Best quality for 1080p modern anime
glsl-shaders="~~/shaders/CfL_Prediction.glsl;~~/shaders/ArtCNN_C4F16.glsl;~~/shaders/adaptive-sharpen.glsl"
scale=ewa_lanczossharp
dscale=mitchell
linear-downscaling=no
scale-antiring=0.6

[Nuvex-480p-1440p-Cel]
profile-desc=Better clarity for 480p Cel Anime
glsl-shaders="~~/shaders/KrigBilateral.glsl;~~/shaders/FSRCNNX_x2_8-0-4-1.glsl;~~/shaders/adaptive-sharpen.glsl"
deband=yes
deband-iterations=4
deband-threshold=48
deband-range=16
deband-grain=24

[HDR]
profile-desc=HDR Optimization
profile-cond=(p["video-params/primaries"] == "bt.2020") and (p["video-params/gamma"] == "pq")
target-trc=pq
target-prim=bt.2020
dither-depth=10
hdr-compute-peak=yes
video-output-levels=full

[HDR-Windows-Only]
profile-cond=(p["video-params/primaries"] == "bt.2020") and os.environ.get('COMSPEC') ~= nil
target-peak=1200
tone-mapping=bt.2390
hdr-compute-peak=yes
sub-hdr-peak=1000
target-contrast=5000
target-colorspace-hint=yes

[4k-Downscaling]
profile-cond=(height >= 2160 or width >= 3840)
profile-restore=copy-equal
glsl-shaders-clr
glsl-shaders="~~/shaders/ssimsr.glsl;~~/shaders/ssimds.glsl"
linear-downscaling=no

[Downmix-Audio-5.1]
profile-cond=get("audio-params/channel-count") >= 5 and get("audio-params/channel-count") < 7
profile-restore=copy-equal
volume-max=200
af=lavfi="lowpass=c=LFE:f=120,volume=1.6,pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE"

[Downmix-Audio-7.1]
profile-cond=get("audio-params/channel-count") >= 7
profile-restore=copy-equal
volume-max=200
af=lavfi="lowpass=c=LFE:f=120,volume=1.6,pan=stereo|FL=0.5*FC+0.3*FLC+0.3*FL+0.3*BL+0.3*SL+0.5*LFE|FR=0.5*FC+0.3*FRC+0.3*FR+0.3*BR+0.3*SR+0.5*LFE"
